import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  ArrowRight, BarChart3, BrainCircuit, CheckCircle2, ClipboardCheck,
  Database, History, Percent, ShieldCheck, Sparkles, Target, Users, UserX,
} from "lucide-react";
import api, { apiErrorMessage } from "../api/api";
import { TrendChart } from "../components/charts/AnalyticsCharts";
import { ChartCard, ErrorState, LoadingSkeleton, StatCard, formatPercent } from "../components/common";
import { useAuth } from "../context/AuthContext";


const processSteps = [
  { icon: Users, title: "Customer Data", text: "Collect demographic, financial and campaign information." },
  { icon: ClipboardCheck, title: "Validation & Preprocessing", text: "Apply the fitted RobustScaler and OneHotEncoder exactly as trained." },
  { icon: BrainCircuit, title: "Random Forest Model", text: "Evaluate 50 processed features through the tuned classifier." },
  { icon: Target, title: "Probability & Explanation", text: "Return the predicted class, likelihood, confidence and global factors." },
  { icon: History, title: "Prediction History", text: "Store successful results securely for future analysis." },
];

export default function HomePage() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [flash] = useState(() => {
    const message = sessionStorage.getItem("tdi_flash");
    sessionStorage.removeItem("tdi_flash");
    return message;
  });
  const { user } = useAuth();

  const load = useCallback(async () => {
    setError("");
    try {
      const [summary, health, activity] = await Promise.all([
        api.get("/api/dashboard/summary"), api.get("/api/health"),
        api.get("/api/analytics/predictions").catch(() => ({ data: null })),
      ]);
      setData({ summary: summary.data, health: health.data, activity: activity.data });
    } catch (requestError) { setError(apiErrorMessage(requestError, "Unable to load the dashboard.")); }
  }, []);

  useEffect(() => { load(); }, [load]);
  const hour = new Date().getHours();
  const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";

  if (error) return <ErrorState message={error} onRetry={load} />;
  if (!data) return <LoadingSkeleton cards={6} label="Loading dashboard" />;
  const { summary, health, activity } = data;
  const activityTotal = activity?.summary?.total_predictions || 0;
  const likelyRate = activityTotal ? activity.summary.likely / activityTotal : 0;

  return (
    <div className="page-stack">
      {flash && <div className="form-alert success"><CheckCircle2 size={17} /> {flash}</div>}
      <section className="hero-card">
        <div className="hero-copy">
          <p className="hero-greeting">{greeting}, {user?.full_name?.split(" ")[0]}</p>
          <p className="eyebrow">Bank Marketing Intelligence</p>
          <h1>Know which conversations are worth starting.</h1>
          <p>Turn customer signals into clear, responsible term-deposit outreach decisions with one focused workspace.</p>
          <div className="hero-actions"><Link className="btn btn-accent" to="/predict"><Sparkles size={18} /> New Prediction <ArrowRight size={17} /></Link><span><i /> Live model connection</span></div>
          <div className="hero-trust">
            <span><ShieldCheck /> Secure analyst workspace</span>
            <span><BarChart3 /> Real dataset intelligence</span>
            <span><CheckCircle2 /> Consistent model pipeline</span>
          </div>
        </div>
        <div className="hero-model-card" aria-label="Model status">
          <span className="model-live"><i /> Model Ready</span>
          <div className="model-orbit"><div><strong>{health.n_features}</strong><span>processed<br />features</span></div></div>
          <div className="hero-model-meta"><span>Random Forest</span><strong>{health.status === "ok" ? "Operational" : "Unavailable"}</strong></div>
        </div>
      </section>

      <section className="stats-grid">
        <StatCard label="Total Predictions" value={summary.total_predictions.toLocaleString()} icon={Database} />
        <StatCard label="Likely to Subscribe" value={summary.likely.toLocaleString()} icon={CheckCircle2} tone="success" />
        <StatCard label="Unlikely to Subscribe" value={summary.unlikely.toLocaleString()} icon={UserX} tone="danger" />
        <StatCard label="Average Probability" value={formatPercent(summary.average_probability)} icon={Percent} tone="gold" />
      </section>

      <section className="home-activity-grid">
        <ChartCard title="Prediction Activity" description="Recent saved predictions generated by your workspace." className="activity-chart">
          {activity?.trend?.length ? <TrendChart data={activity.trend} /> : <div className="chart-empty"><BarChart3 /><strong>No activity yet</strong><span>Your prediction trend will appear after the first analysis.</span></div>}
        </ChartCard>
        <article className="card activity-summary-card">
          <div><p className="eyebrow">Workspace pulse</p><h2>Decision activity</h2><p>A concise view of the prediction history currently available to your account.</p></div>
          <dl>
            <div><dt>Saved predictions</dt><dd>{activityTotal.toLocaleString()}</dd></div>
            <div><dt>Likely outcome rate</dt><dd>{formatPercent(likelyRate)}</dd></div>
            <div><dt>Average probability</dt><dd>{formatPercent(activity?.summary?.average_probability)}</dd></div>
          </dl>
          <Link className="text-link" to="/history">Review prediction history <ArrowRight size={16} /></Link>
        </article>
      </section>

      <section className="card section-card">
        <div className="section-heading"><div><p className="eyebrow">ML workflow</p><h2>How the System Works</h2><p>One traceable process from customer inputs to stored decision support.</p></div></div>
        <div className="process-grid">
          {processSteps.map(({ icon: Icon, title, text }, index) => (
            <article className="process-step" key={title}>
              <span className="step-number">{String(index + 1).padStart(2, "0")}</span>
              <span className="step-icon"><Icon size={21} /></span>
              <h3>{title}</h3><p>{text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="card model-card">
        <div className="model-card-title"><span><BrainCircuit /></span><div><p className="eyebrow">Production pipeline</p><h2>Model Information</h2><p>Live status is checked directly from the FastAPI backend.</p></div></div>
        <dl className="model-metrics">
          <div><dt>Model</dt><dd>{health.model}</dd></div>
          <div><dt>Model Features</dt><dd>{health.n_features}</dd></div>
          <div><dt>Prediction Threshold</dt><dd>50%</dd></div>
          <div><dt>Model Status</dt><dd className="status-ready"><span /> {health.status === "ok" ? "Ready" : "Unavailable"}</dd></div>
        </dl>
      </section>
    </div>
  );
}
